project:
  type: website
  output-dir: _site

website:
  title: "Rides dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: false

execute:
  freeze: auto
